services:
  - type: web
    name: ai-business-automation-api
    env: python
    region: oregon
    plan: free
    branch: beta
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_API_KEY
        sync: false  # Set this in Render dashboard
    healthCheckPath: /health
